name: Detect Latex, Create PR
on:
  issue_comment:
    types:
      - created
      - edited
jobs:
  detect-latex:
    runs-on: ubuntu-latest
    if: startsWith( github.event.comment.body, '\documentclass' )
    env:
      FILE: ${{ format( 'Src/Pages/{0}.tex', github.event.issue.title ) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add LaTeX
        run: |
          mkdir -p Src/Pages
          cat > $FILE << EOF
          ${{ github.event.comment.body }}
          EOF
      - name: Tectonic Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-tectonic-
      - name: Setup tectonic
        uses: wtfjoke/setup-tectonic@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check If Page compiles (Tectonic)
        run: tectonic $FILE | awk '{ print "CompileOutput="$1 }' >> $GITHUB_ENV; test ${PIPESTATUS[0]} -eq 0
      - name: If Check failed, Comment error
        if: ${{ failure() }}
        uses: ben-z/actions-comment-on-issue@1.0.2
        with:
          message: "# There was an error in submited code\n ${{ env.CompileOutput }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Raw Page 
        run: .github/scripts/updateRawPage.sh $FILE
      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          branch: ${{ format( 'page-fix/{0}', github.event.issue.title) }} 
          title: ${{ format( 'Add LaTeX of pages {0}', github.event.issue.title ) }}
          body: "Automated change, triggered by $\\LaTeX$ comment on Issue"
