name: Split Book.pdf
on:
  push:
    paths: 'Book.pdf'
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  split-book:
    runs-on: ubuntu-latest
    steps:
      - name: Install PDFtk
        uses: ConorMacBride/install-package@v1
        with:
          apt: pdftk
      - name: Checkout
        uses: actions/checkout@v3
      - name: Split to Pages
        run: .github/scripts/splitBook.sh Book.pdf 5
      - name: Remove Book.pdf
        run: rm Book.pdf
      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Remove Book.pdf, Add Parts'
      - name: Fix Labels
        run: .github/scripts/fixLabels.sh
      - name: Automaticaly Create Issues
        run: gh workflow run createLaTeXIssues.yml
